version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    web:
        image: nginx:stable
        container_name: laravel-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:16
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: company_browser_api
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose:
            -   "5433"
        ports:
            - "5433:5432"
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
